### ISSUE TITLE
Rust release-party in Munich: Planning (2015-05-15)

### ISSUE THREAD

**Issue by Byron** [Byron/depot#1]
This ticket keeps track of the planning stage for the Rust release party in Munich. We will find a good location, and keep track of all the people interested in joining as well.
If there is anything you want to add, please leave a comment and I will update the ticket accordingly.
# Where

Possible locations are listed here. If you have something to add, just put it into the comment and I will put it here.
## Café Mozart
- cosy and big enough to hold even larger groups
- quite central, and other locations like Clubs are not far away
# When

Friday, 15th of May, 2015, at **8pm** seems good to me. We might have food there as well, as feast + beer + party seems like something I'd like to do :).
Names written like _(this)_ are tentative.
## Attendees
- @Byron
- @HeeL 
- @bascht 
- @fhinkel
- @Dean4Devil 
- @michaelwoerister 
- @tomprogrammer 
- @vmx 
- @lassej 
- @Rahix 
- ~~@ujh~~
- (_@MarkusJais_)
- _(@grandcat)_

**Comment by HeeL** [comment]
Awesome, I'm in!

**Comment by grandcat** [comment]
Would definitely be interested, too!
However, not sure whether it works out.

**Comment by bascht** [comment]
Glad I googled for it! I'd like to join as well. :-)

**Comment by Byron** [comment]
Great you googled too ! We are reaching critical mass :) !

**Comment by ujh** [comment]
Awesome! @skade pointed this out to me. I'm in, too!

**Comment by Byron** [comment]
Welcome !
Using github to plan a developer meetup is not the worst thing ! Especially considering the market leader meetup.com charges you for any group you create.

**Comment by skade** [comment]
@byron I don't necessarily agree.

As much as I hate them, meetup is very good a propagating events and reaching audience. As far as I know, I still have an open slot on my account that I'd be willing to give away. I still hate them with a passion, though. :)

Another option is http://www.doorkeeperhq.com/

A third option in the long run is use something like onruby: http://www.onruby.de/ It's an open source multi-tenant UG organisation tool (it's coupled to Ruby only in naming and implementation). It's rather easy to setup an operate and keeps a certain level of independence from commercial vendors. If anyone would be interested, we could go for something like that.

**Comment by HeeL** [comment]
Heh, more and more Ruby devs are attending

**Comment by Byron** [comment]
@skade Thanks for the write-up, I didn't know about the alternatives at all !
Hate is a strong word, and as far as meetup.co goes I'd say their web platform is quite poor compared to something like github for example.

However, if you wouldn't mind you could be the organizer of the official Rust-Munich meetup.com. I had plans to make one myself, but I'd gladly co-organize it with you. As I have quite a few connections by now it shouldn't be a problem to get hosted, with pizza and beer and such (at least for the non-party meetups). The party will probably work without meetup.com, yet I would like to make this a starting point for the Rust community in Munich to evolve. Lets definitely talk about it during the party event.

@HeeL Damn that spelling correction, Rust devs, you mean ;) ! Just kidding, send them over please, to the _Social Issue™_

**Comment by skade** [comment]
@byron Well, I am not in Munich. But I run a couple of other things (that's where the hate comes from, it's really poor at some points...), so I have free slots I can offer just as the hosting. That would _formally_ be main organiser for meetup, but nothing more. I'll see if I can set something up later this week.

**Comment by Byron** [comment]
@skade Oh, I see, I missed you are not actually on the attendee list either. Thanks for helping out with meetup.com, it's much appreciated !

**Comment by oli-obk** [comment]
:( 60EUR just for bahn travels there and back. Anyone happing to travel there from Baden Württemberg?

**Comment by fhinkel** [comment]
I'm in!

**Comment by Byron** [comment]
A warm welcome to the one who seems to have coined `In Rust I trust` for the first time !

**Comment by fhinkel** [comment]
😊 Thank you!

**Comment by dequbed** [comment]
Count me in too, please! :)

**Comment by Byron** [comment]
Welcome ! Quite a respectable group-size already !

**Comment by michaelwoerister** [comment]
I'll be there too. I thought about organizing a meetup in Vienna but then didn't find the time. I'm glad there's another one nearby :)

**Comment by Byron** [comment]
Welcome and cheers to Vienna ! Please note that we are meeting in Café Mozart at Pettenkoferstr., not the one in Vienna ;). Even though I wished it was the other way around, after all I have never been there.

**Comment by tomprogrammer** [comment]
Great that there is a release party here!
I'd like to attend too. :)

I've found it in TWIR (This week in Rust).

**Comment by Byron** [comment]
Welcome ! If this meetup keeps growing at this pace, we will need a bigger table ;) ! Of course I didn't reserve yet, but hope that 3 to 4 days before _the night_ I can estimate the final group size.

**Comment by vmx** [comment]
I'm in as well. Good to see some Rusticians from the area.

**Comment by Byron** [comment]
Welcome @vmx ! I am looking forward to seeing all of you !

**Comment by lassej** [comment]
I'd like to come, too!

**Comment by Byron** [comment]
Welcome @lassej !

**Comment by Rahix** [comment]
I think I'll be there too.

**Comment by Byron** [comment]
Welcome @Rahix  !

**Comment by ujh** [comment]
Unfortunately I won't be able to make it as I've sprained my foot. Have fun nonetheless and maybe we'll be able to have a Rust meetup here in Munich and meet then. :)

**Comment by Byron** [comment]
Ouch, be well soon ! However, we will take some pictures and twitter them to @rustlang - if you don't follow them yet, this might be a good occasion.

**Comment by Byron** [comment]
The table is booked for **Friday**, 15th of May 2015 **from 8pm**, big enough to provide space for 12 people, at least. In case you are there earlier, you may ask for the table booked by me, _Sebastian Thiel_.
They also have a menu in case you want to eat something.

See you all on Friday, it's going to be fun !

PS: Besides the table, I have accounted for absolutely nothing. If you have ideas that require additional preparation, we can discuss this here as well.

**Comment by MarkusJais** [comment]
I hope I can come as well but will have to decide on short notice as I don't know how long I will be at another appointment.

**Comment by Byron** [comment]
Feel free to join, there should be a few free seats.

**Comment by MarkusJais** [comment]
Just to let you know. Just created a Rust Meetup Group in Munich:

http://www.meetup.com/Munchen-Rust-Meetup/

Currently 50 members maximum but I will expand it immediately should we reach that number.
Please only sign up if you plan to come to meetings.

**Comment by HeeL** [comment]
@MarkusJais, cool, that's the spirit! Please create an album for meetup so people can do uploads

**Comment by MarkusJais** [comment]
I will try to setup everything as good as possible. Meetup UI is weird :-)

**Comment by skade** [comment]
@MarkusJais You maybe should setup a meeting on meetup for tomorrow to make sure it goes out via their email.

**Comment by MarkusJais** [comment]
@skade Done via Meetup. Just as a reminder, I asked everyone to sing up here as reservations have already been made and I don't want to make it confusing with two websites :-)

**Comment by Byron** [comment]
![img_7029](https://cloud.githubusercontent.com/assets/63622/7665039/949fdc20-fba6-11e4-8804-e42b620a8f33.jpg)
![img_6912](https://cloud.githubusercontent.com/assets/63622/7665040/94aeb362-fba6-11e4-869f-06bd9575c3c8.jpg)
![img_7026](https://cloud.githubusercontent.com/assets/63622/7665096/0309dc68-fba9-11e4-915c-08f29f4e7f62.jpg)

![img_7065](https://cloud.githubusercontent.com/assets/63622/7665097/0a0ed734-fba9-11e4-906c-f3fc560cf948.jpg)

![img_6940](https://cloud.githubusercontent.com/assets/63622/7665100/13b104f6-fba9-11e4-8612-68e21c1aba00.jpg)

![img_7018](https://cloud.githubusercontent.com/assets/63622/7665102/196cf3b4-fba9-11e4-90c5-c24635291309.jpg)

![img_7034](https://cloud.githubusercontent.com/assets/63622/7665041/94bf13b0-fba6-11e4-8fb7-34a73cae268f.jpg)
![img_7101](https://cloud.githubusercontent.com/assets/63622/7665042/94cbf242-fba6-11e4-8095-56f910d9fd84.jpg)
![img_7055](https://cloud.githubusercontent.com/assets/63622/7665103/1ea0a77c-fba9-11e4-986d-70c49c777b7c.jpg)

![img_6952](https://cloud.githubusercontent.com/assets/63622/7665104/2311e7b2-fba9-11e4-87c3-d10cf80d4fad.jpg)

**Comment by Byron** [comment]
Thanks everyone for coming ! I had great fun - finally one can be around think-alikes ! Lets repeat this soon, and organize ourselves through the [Rust Munich](http://www.meetup.com/rust-munich/) meetup group !

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/W5rreAyeTXg).

_`Looksies #6 [Let's look at the Rust-Doom]`_

[![thumb](https://i.ytimg.com/vi/W5rreAyeTXg/mqdefault.jpg)](https://youtu.be/W5rreAyeTXg)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/rgcdzwuNR5o).

_`Hacks #3 [improving mandelbrot performance [FAIL]]`_

[![thumb](https://i.ytimg.com/vi/rgcdzwuNR5o/mqdefault.jpg)](https://youtu.be/rgcdzwuNR5o)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/AIxfELqOZXY).

_`Looksies #8 [Let's look at the mooneye-gb]`_

[![thumb](https://i.ytimg.com/vi/AIxfELqOZXY/mqdefault.jpg)](https://youtu.be/AIxfELqOZXY)
